model:
    arch: bisenet_v2
weight_init_t:
    rpnet_c: '../runs/hardnet/cur/MybestSoFar.pkl'
    dlinknet_34: '../runs/hardnet/cur/Mybest_19600.pkl'
    erfnet: '../runs/hardnet/cur/Mybest_6000.pkl'
    bisenet_v2: -1
weight_init_p:
    rpnet_c: '../runs/hardnet/cur/hardnet_best.pkl'
    dlinknet_34: -1
    erfnet: '../runs/hardnet/cur/erfnet.pth'
    bisenet_v2: -1
data:
    dataset: railsem19_seg_triplet_b
    train_split: train
    val_split: val
    img_rows: 540
    img_cols: 960
    path: None
    sbd_path: None
training:
    num_seg_classes: 3
    num_reg_channels: 1
    train_iters: 90000
    batch_size: 8
    val_interval: 100
    n_workers: 0
    print_interval: 100
    optimizer:
        name: 'adam'
        adam:
            lr: 0.01
            weight_decay: 0.0005
        sgd:
            lr: 0.001
            weight_decay: 0.0005
            momentum: 0.9
    loss:
        name: 'bootstrapped_cross_entropy'
        min_K: 8192
        loss_th: 0.3
        size_average: True
        train_val: 0
    lr_schedule: 
        name: 'poly_lr'
        max_iter: 90000
    resume: None
    finetune: None
